### ISSUE TITLE
nothing appears except little squares

### ISSUE THREAD

**Issue by DilaraAlbayrak** [amarlearning/Finger-Detection-and-Tracking#8]
I have run the code with no error but nothing happens?

**Comment by antoineFrau** [comment]
Just read the code : 
```
def main():
    if pressed_key & 0xFF == ord('z'):
                is_hand_hist_created = True
                hand_hist = hand_histogram(frame)
     if is_hand_hist_created:
                manage_image_opr(frame, hand_hist)
```
You need to press "z" to proceed the detection.

**Comment by amarlearning** [comment]
@DilaraSina When you run the code you will see 9 square blocks in the screen, now you have to cover the squares with your hand so that the program can detect your skin color based on your present lighting conditions.

Let me know if you still face any issue.

@antoineFrau Thanks for your help :smile:

**Comment by DilaraSina** [comment]
sorry for misleading explanation, I was in hurry, I could not explain properly. Of course I pressed 'z', in that case nothing happened. @amarlearning now I have placed my hand so that it covers 9 squares but no tracking appears, yellow dots appear but it does not seem like the dots track my fingers.

**Comment by amarlearning** [comment]
@DilaraSina It's actually the background. Try with a plain background as much as possible.﻿

**Comment by DilaraSina** [comment]
Thank you, I will try and update here

**Comment by manish-singla** [comment]
@DilaraSina  you are right. I also faced the same issue. @amarlearning  tried it with a plain background but still no help!!

**Comment by amarlearning** [comment]
[Fixed](https://github.com/amarlearning/Finger-Detection-and-Tracking/commit/c4e944d4b02575555b812e9341c774bb07d2c08b)
